version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - TZ=America/Whitehorse
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    env_file:
      - db/sapassword.env
    user: root
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
